# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lariat', '0002_auto_20170727_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ssn4',
            new_name='ssn',
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
