# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lariat', '0005_auto_20170727_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='snf',
            field=models.CharField(default='no', help_text='snf', max_length=3),
            preserve_default=False,
        ),
    ]
