# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lariat', '0006_patient_snf'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='osaa',
            field=models.BooleanField(default=False),
        ),
    ]
