# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lariat', '0008_auto_20171024_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nephrologist',
            field=models.BooleanField(default=False, help_text='Any History of Kidney disease?'),
        ),
    ]
