# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lariat', '0009_auto_20171024_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cancer',
            field=models.CharField(default='no', help_text='cancer', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='chf',
            field=models.CharField(default='no', help_text='CHF', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sob',
            field=models.CharField(default='no', help_text='sob', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='nephrologist',
            field=models.CharField(max_length=3),
        ),
    ]
