# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lariat', '0011_auto_20171024_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appetite',
            field=models.CharField(default='no', help_text='appetite', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_loss',
            field=models.CharField(default='no', help_text='cancer', max_length=3),
        ),
    ]
