# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lariat', '0012_auto_20171024_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='active_smoker',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='climb2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='osa',
        ),
    ]
